# yaml-language-server: $schema=https://apps.kelvininc.com/schemas/kelvin/5.0.0/app.json
spec_version: 5.0.0
type: app

# ------------------------------------------------------------------------------
# Basic Information
# ------------------------------------------------------------------------------
name: speed-multiplier
title: Mill Speed Multiplier
description: This is an example mill speed multiplier for demonstration purposes.
version: 1.0.5

# ------------------------------------------------------------------------------
# Application Capabilities
# ------------------------------------------------------------------------------
flags:
  enable_runtime_update:
    configuration: false # Reload application configuration at runtime (without restart).
    parameters: true # Reload application parameters at runtime (without restart).
    resources: true # Deploy new assets at runtime (restart required).
    resource_properties: true # Reload asset properties at runtime (without restart).

# ------------------------------------------------------------------------------
# Datastream Definitions
# ------------------------------------------------------------------------------
data_streams:
  inputs: # Application consumes motor temperature and speed data.
    - name: mill_speed
      data_type: number

  outputs:
    - name: output
      data_type: number

# ------------------------------------------------------------------------------
# Control Changes Definitions
# ------------------------------------------------------------------------------
control_changes:
  inputs: []
  outputs: []

# ------------------------------------------------------------------------------
# Custom Actions Definitions
# ------------------------------------------------------------------------------
custom_actions:
  inputs: []
  outputs: []

# ------------------------------------------------------------------------------
# Application-Asset Parameters Definitions
# ------------------------------------------------------------------------------
parameters:
  - name: multiplier 
    data_type: number

# ------------------------------------------------------------------------------
# UI Schemas (Optional)
# ------------------------------------------------------------------------------
ui_schemas:
  # Define paths to UI schemas for optional configuration and parameter management.
  # configuration: "ui_schemas/configuration.json"
  parameters: "ui_schemas/parameters.json"

# ------------------------------------------------------------------------------
# Default Settings (Runtime/Deployment)
# ------------------------------------------------------------------------------
defaults:
  configuration: {} # Default values for application configuration.

  parameters: # Default values for application parameters.
    multiplier: 10

  system: {} # Default system settings (CPU/Memory Limits, Ports, Volumes, Environment Variables, etc).
