# yaml-language-server: $schema=https://apps.kelvininc.com/schemas/kelvin/5.0.0/app.json
spec_version: 5.0.0
type: app

# ------------------------------------------------------------------------------
# Basic Information
# ------------------------------------------------------------------------------
name: hello-app
title: Hello App
description: This is a hello app for demonstration purposes.
version: 1.0.0

# ------------------------------------------------------------------------------
# Application Capabilities
# ------------------------------------------------------------------------------
flags:
  enable_runtime_update:
    configuration: false # Reload application configuration at runtime (without restart).
    parameters: true # Reload application parameters at runtime (without restart).
    resources: false # Deploy new assets at runtime (restart required).
    resource_properties: true # Reload asset properties at runtime (without restart).

# ------------------------------------------------------------------------------
# Datastream Definitions
# ------------------------------------------------------------------------------
data_streams:
  inputs:
    - name: motor_temperature # Application consumes motor temperature data.
      data_type: number

  outputs: []

# ------------------------------------------------------------------------------
# Control Changes Definitions
# ------------------------------------------------------------------------------
control_changes:
  inputs: []
  outputs:
    - name: motor_speed_set_point # Control output for setting motor speed.
      data_type: number

# ------------------------------------------------------------------------------
# Application-Asset Parameters Definitions
# ------------------------------------------------------------------------------
parameters:
  - name: kelvin_control_mode
    data_type: string
  - name: temperature_max_threshold
    data_type: number

# ------------------------------------------------------------------------------
# UI Schemas (Optional)
# ------------------------------------------------------------------------------
ui_schemas:
  # Define paths to UI schemas for optional configuration and parameter management.
  # configuration: "ui_schemas/configuration.json"
  parameters: "ui_schemas/parameters.json"

# ------------------------------------------------------------------------------
# Default Settings (Runtime/Deployment)
# ------------------------------------------------------------------------------
defaults:
  configuration: {} # Default values for application configuration.

  parameters: # Default values for application parameters.
    closed_loop: false
    temperature_max_threshold: 59

  system: {} # Default system settings (CPU/Memory Limits, Ports, Volumes, Environment Variables, etc).
